= Distributed Switch Architecture Testing framework

_dsatest_ is a network test framework targeting Linux machines featuring one or
more managed Ethernet switch chips. It is designed to be simple, no complex
topology is required. A single *host* machine running the tests must be
connected to the switch ports of a single *target* machine under test.

== Getting started

The framework depends on `python-paramiko`. Once installed, you can skip the
SSH connection and run all sanity tests with:

[source,sh]
----
./dsatest --dry-run -t sanity.py -B bench.cfg.example
----

== Configuration files

Three kind of files need to be populated in order to run tests on the bench.
From a bottom-up approach:

Switch::
describe a switch and how its kernel driver exposes some information. This file 
can be shared and used in several test benches.
Target::
describe the machine being tested, the switches that are on it, and the 
interfaces that the test bench will be able to use. This file can also be 
shared.
Bench::
describe how the host machine and the target machine are connected to one 
another. This file is specific to each bench.

=== Switch

*TODO: Not used yet*

They are located in `conf/switch/`. An example switch may look like this:

----
  +----------------+
  |          port0 |----> CPU port
  | SWITCH   port1 |----> User port #0
  |          port2 |----> User port #1
  |          port3 |----> User port #2
  +----------------+
----

See link:conf/switch/example-switch.cfg[].

=== Target

They are located in `conf/target/`. They describe the hardware of the
machine being tested. For instance, consider the following situation:

----
  +--------------------------------------------------+
  |                       TARGET                     |
  |  +----------------+                              |
  |  |          port0 |----> to CPU                  |
  |  | switch0  port1 |--------------------------[ link0 ] <-+
  |  |          port2 |----> Non connected           |       |- connectors
  |  |          port3 |--------------------------[ link1 ] <-+   (eg. RJ45)
  |  +----------------+                              |
  +--------------------------------------------------+
----

Only port1 and port3 of switch0 are connected to front-facing connectors.
Obviously the bench can only use these two ports to run tests.

Describing the internals of the target (which switch port is connected to what
front-facing connector) allows to get sensible error reporting if errors occur.
Moreover, these files can be shared by people using the same hardware.

See link:conf/target/example-target.cfg[].

=== Bench

Describe the test bench, ie. how the controlling machine (aka host), running
dsatest, is connected to the target machine.

For instance, let's create a test bench with the target defined in the previous
section. Host and Target are connected with only one cable:

----
  +-------------+                        +---------------+
  |             |         cable          |               |
  |          [ eth8 ]<------------>[ enp0s31f6 ]         |
  |   TARGET    |         link0          |               |
  |          [ eth9 ]                    |      HOST     |
  |             |                        |               |
  +-------------+                        +---------------+
----

Bench configuration file defines that link0 is eth8 on the target side, and
enp0s31f6 on host side. eth9 is left disconnected. Names of interfaces is
defined at the bench level because interfaces may have different names
depending on the OS running on it, so it may vary from one test bench to
another.

See link:bench.cfg.example[].

When a link is defined under both the host and the target section, dsatest will
register that link and the corresponding interfaces so that tests will be able
to use them. Links connected to only one end will be ignored.

== usage

Note that you need the `NET_CAP_ADMIN` capability in order to configure network
interfaces.

[source,sh]
----
# run all tests containing "ping" in their test method names
mv bench.cfg.example bench.cfg
./bench.sh -t ping
----

=== Out-of-tree configuration

One can use out-of-tree configuration files by using the `-C` or `--conf-dir`
flags and specifying a directory that has the same layout as the `conf/`
directory. Files found in this alternate directory will have precedence over the
ones found in dsatest's `conf` directory.


== Tests

Tests are written using unittest, and must respect rules defined by this module.
They can access the test bench instance through the following import:

[source,python]
----
from dsatest.bench import bench
----

API is self-documented in `test/sanity.py`. More documentation welcome!
